### ISSUE TITLE
Add regtest support

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingolib#12]
I think the way forward is a 'Regtest' variant added to the Network enum:

https://github.com/zingolabs/zingolib/blob/8c49caea0d82d3c795a8cd557d80cc9bf2c8a3e4/config/src/lib.rs#L9-L14

**Comment by dannasessha** [comment]
Acknowledged.

**Comment by dannasessha** [comment]
I continued with this idea on #8. I would like a review from someone and maybe they could add "fixes #12" if indeed it does. :)

https://github.com/zingolabs/zingolib/pull/8#issuecomment-1169591694

**Comment by dannasessha** [comment]
Seems to be solved on #8 . Closing.
