### ISSUE TITLE
Fee erroneous to have balance in Sapling and Orchard and Send all.

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingolib#1233]
In the last tests made to the Beta RC version I could see that the fee calculation with the ZIP 317 is working quite well, but there is a problem, when you have balance in Sapling and Orchard and you try to Send everything having activated the option Donate to ZingoLabs, the fee calculation gives error.

### Requirements:
- Have balance in Sapling.
- Activate the Send All function from Settings.
- Activate the Donate to ZingoLabs option from Settings.

### Steps to reproduce the error:

1. Click on Send
2. Paste a unified address that has Orchard receiver.
3. Click on Send All

### Current behavior:

You will be able to see that tapping on Send All causes the fee calculation to error (shown in red).

### Expected behavior:

The fee calculation should be correct since when Send all the fee deduction should be made according to the inputs and outputs of the transaction.

### IMPORTANT:
This error only occurs when the address is unified with Orchard receiver (Zingo sends funds to Orchard by default), with Z (Sapling) and T (Transparent) address the fee calculation is correct.

### Demo:

https://github.com/zingolabs/zingolib/assets/37910384/e14e78e0-91a6-4e87-95df-04558ee45cc1

**Comment by zancas** [comment]
This is in the case of the `Zennies for Zingo` donation option being turned on?

**Comment by Oscar-Pepper** [comment]
its important to note this is not really a bug, this is just not implemented. i will discuss the correct fix at codeshare

**Comment by juanky201271** [comment]
> This is in the case of the `Zennies for Zingo` donation option being turned on?

Yes, this is the case. As @Oscar-Pepper said the `spendablebalance` command only works with one receiver (address), the `sendall` command only works for one receiver as well, but the `send` (proposal) command return the fee for 1 or more receivers (addresses).
It is just not implemented.
