### ISSUE TITLE
Track future work from the UnifiedSpendAuthority PR

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#139]
* construct 8-possibility receiver-selection test fixture
* for `scan_bundle` does the parameter list make sense if "unconfirmed" is true?
* can we entirely-or-mostly separate "unconfirmed" logic into its own fn-or-method?

**Comment by AloeareV** [comment]
Test of fn `get_zaddr_from_bip39_seed`

**Comment by jarys** [comment]
replacing `UnifiedSpendAuthority` with `WalletCapability` in
- #241
