### ISSUE TITLE
ZIP 320 manual testing ultimate Issues

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#1483]
1. I can see the `refund` transparent addresses in the Value Transfers List instead a `send-to-self` transaction without address.
2. The transmitted transactions aren't persistent when you close/open the App. (Intermittent behavior). 
3. When the first transaction is confirmed I can see a transparent amount and I can shield it, if I do, the shield transaction is confirmed and the second transmitted transaction disappears. 
4. When the fist transaction is confirmed I can send funds to another address, if I do, the send transaction is confirmed and the second transmitted transaction stays in the history immutable for hours, and finally disappears.

@Edicksonjga Maybe you have more or another issues...

**Comment by zancas** [comment]
Really nice work!

I'd like to work out a road map where eventually all of these states are scripted in an emulator and asserted to be correct.

I *think* detox tests might permit that?

@Edicksonjga @juanky201271 @dorianvp 

Can we meet to discuss the work that remains to get to that point for our test harness?

**Comment by zancas** [comment]
I see this as a cross-repo concern.

I believe we need to have automated tests running on an emulated app that verify the state of each of these flows.  (In zingo-mobile?)

I believe that these issues should properly be fixed in zingolib.

**Comment by fluidvanadium** [comment]
i am sure, based on edicksonz results, that 3 and 4 are due to #1437

**Comment by juanky201271** [comment]
> I see this as a cross-repo concern.
> 
> I believe we need to have automated tests running on an emulated app that verify the state of each of these flows. (In zingo-mobile?)
> 
> I believe that these issues should properly be fixed in zingolib.

I'm working on e2e test for those flows... in zingo-mobile.

**Comment by juanky201271** [comment]
about the number 1 issue I noticed something interesting... 2 different scenarios:
- If you update the App normally and you have your wallet there, when you send to TEX sometimes (maybe always...) you can see the `refund` address.
- If you install the App and restore from seed OR if you run a Rescan with the new version of the App, when you send to TEX you always see the `send-to-self` transaction and you DO NOT see the `refund` addresses at all.

I hope this make sense to someone... @zancas @fluidvanadium @AloeareV

**Comment by juanky201271** [comment]
Update:
1. Solved. I don't see this anymore.
2. I keep see this in the lasts manual testings.
3. & 4. I think these are not Bugs, just the normal behavior of creating two sequential transactions... obviously if the seconds one take a bit more time, the user can do actions with the App. I think these are hard to prevent.

**Comment by juanky201271** [comment]
Update:
2. Solved. I don't see this anymore.

Closing...
