### ISSUE TITLE
Test Is Failing on Dev

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#1491]
cargo nextest run slow::mempool_clearing_and_full_batch_syncs_correct_trees
    Finished `test` profile [optimized] target(s) in 0.11s
------------
 Nextest run ID 60fe83ee-7905-4f82-99bf-c6c57d969bfd with nextest profile: default
    Starting 1 test across 18 binaries (360 tests skipped)
        SLOW [> 60.000s] libtonode-tests::concrete slow::mempool_clearing_and_full_batch_syncs_correct_trees
        SLOW [>120.000s] libtonode-tests::concrete slow::mempool_clearing_and_full_batch_syncs_correct_trees
        FAIL [ 124.042s] libtonode-tests::concrete slow::mempool_clearing_and_full_batch_syncs_correct_trees

--- STDOUT:              libtonode-tests::concrete slow::mempool_clearing_and_full_batch_syncs_correct_trees ---

running 1 test
test slow::mempool_clearing_and_full_batch_syncs_correct_trees has been running for over 60 seconds
{
    "unspent_sapling_notes": [],
    "pending_sapling_notes": [],
    "unspent_orchard_notes": [
        {
            "created_in_block": 11,
            "datetime": 1730500932,
            "created_in_txid": "6b4ef1c45d210d9329e078c172ebefeca5147ddb6aabaf6ab84ac69cefbcf401",
            "value": 10,
            "pending": false,
            "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8",
            "spendable": false,
            "spent": null,
            "pending_spent": null,
            "spent_at_height": null
        },
        {
            "created_in_block": 12,
            "datetime": 1730500963,
            "created_in_txid": "fc46978ae4a458ee9a019ef44a4ed5ab338e5656d064ebb0828da80fec48c739",
            "value": 67990,
            "pending": true,
            "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8",
            "spendable": false,
            "spent": null,
            "pending_spent": null,
            "spent_at_height": null
        }
    ],
    "pending_orchard_notes": [
        {
            "created_in_block": 11,
            "datetime": 1730500932,
            "created_in_txid": "6b4ef1c45d210d9329e078c172ebefeca5147ddb6aabaf6ab84ac69cefbcf401",
            "value": 89990,
            "pending": false,
            "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8",
            "spendable": false,
            "spent": null,
            "pending_spent": "fc46978ae4a458ee9a019ef44a4ed5ab338e5656d064ebb0828da80fec48c739",
            "spent_at_height": 12
        }
    ],
    "utxos": [],
    "pending_utxos": [],
    "spent_sapling_notes": [],
    "spent_orchard_notes": [
        {
            "created_in_block": 5,
            "datetime": 1730500913,
            "created_in_txid": "61b80b8a26b997dd7668ed21909c089019a83a4e113e1f6ea90f3dbdb2cf5b51",
            "value": 100000,
            "pending": false,
            "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8",
            "spendable": false,
            "spent": "6b4ef1c45d210d9329e078c172ebefeca5147ddb6aabaf6ab84ac69cefbcf401",
            "pending_spent": null,
            "spent_at_height": 11
        }
    ],
    "spent_utxos": []
}
[
    {
        "outgoing_metadata": [],
        "amount": 100000,
        "memo": "null, null",
        "block_height": 5,
        "pending": false,
        "datetime": 1730500913,
        "position": 0,
        "txid": "61b80b8a26b997dd7668ed21909c089019a83a4e113e1f6ea90f3dbdb2cf5b51",
        "zec_price": null,
        "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8"
    },
    {
        "outgoing_metadata": [],
        "amount": -10000,
        "memo": "Wallet-internal memo, null, null",
        "block_height": 11,
        "pending": false,
        "datetime": 1730500932,
        "position": 0,
        "txid": "6b4ef1c45d210d9329e078c172ebefeca5147ddb6aabaf6ab84ac69cefbcf401",
        "zec_price": null,
        "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8"
    },
    {
        "outgoing_metadata": [
            {
                "address": "zregtestsapling1fmq2ufux3gm0v8qf7x585wj56le4wjfsqsj27zprjghntrerntggg507hxh2ydcdkn7sx8kya7p",
                "value": 2000,
                "memo": "Outgoing Memo"
            }
        ],
        "amount": -22000,
        "memo": "Wallet-internal memo, null",
        "block_height": 12,
        "pending": true,
        "datetime": 1730500963,
        "position": 0,
        "txid": "fc46978ae4a458ee9a019ef44a4ed5ab338e5656d064ebb0828da80fec48c739",
        "zec_price": null,
        "address": "uregtest1wdukkmv5p5n824e8ytnc3m6m77v9vwwl7hcpj0wangf6z23f9x0fnaen625dxgn8cgp67vzw6swuar6uwp3nqywfvvkuqrhdjffxjfg644uthqazrtxhrgwac0a6ujzgwp8y9cwthjeayq8r0q6786yugzzyt9vevxn7peujlw8kp3vf6d8p4fvvpd8qd5p7xt2uagelmtf3vl6w3u8"
    }
]
Removing expired mempool tx fc46978ae4a458ee9a019ef44a4ed5ab338e5656d064ebb0828da80fec48c739
test slow::mempool_clearing_and_full_batch_syncs_correct_trees ... FAILED

failures:

failures:
    slow::mempool_clearing_and_full_batch_syncs_correct_trees

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 61 filtered out; finished in 124.03s

--- STDERR:              libtonode-tests::concrete slow::mempool_clearing_and_full_batch_syncs_correct_trees ---
thread 'slow::mempool_clearing_and_full_batch_syncs_correct_trees' panicked at libtonode-tests/tests/concrete.rs:2645:9:
assertion `left == right` failed
  left: Some(MerklePath { path_elems: [MerkleHashOrchard(0x3e492341cfd8ec2187a2717669e6433fe4a9cb8213140b5272f57ffdeeae21cd), MerkleHashOrchard(0x11f4976cde2d797fccb9514e3858c906cbbd9f5e520f003c71c209c80725abd1), MerkleHashOrchard(0x06edb1a36127329f3e6b84ca0c3e23a114670994f97a6c1a1b16412f4d2b6974), MerkleHashOrchard(0x345e01fef477441282acd370433e6de39b3e5b92ff5bf230920ddee17f6a01a0), MerkleHashOrchard(0x31b4ea3aced9464a3daba756ae9945b86407f3ef514c38f2d4645cb4fefb6a80), MerkleHashOrchard(0x18abed52ed3002af2798f51bc19bedd2c9fc69003699e845c6f0c0f257413e87), MerkleHashOrchard(0x02c4ff95a4f8937220846aa30a8abc6fa8a053125ac1c870ade13a952013ab27), MerkleHashOrchard(0x3b13f3906f701d1f8e4ad7221b0555056830523b11374b5ba6a291f13d56144e), MerkleHashOrchard(0x1f3707da6df0e41c6f67045d859633ce55851d4b17f4b74e0f8ad193f9e4bbb3), MerkleHashOrchard(0x0e17bd4c92572b5a39b8bc1c99cbdf79c628ba3fe9279eeb6ad7f0c6e9bdf54e), MerkleHashOrchard(0x0743b7c639f9a56294bf11831b6a7da417d27c7d6a0dc31ecaf5ebac6825c0a3), MerkleHashOrchard(0x390dd1d2c5662b30f61c6ca9ca404d1db4495decd6ba0516da2261ae0bb3f93e), MerkleHashOrchard(0x0b9ed98ef64fa6a78488390038e530982d3670de72c1703be6ab93cb0028ae22), MerkleHashOrchard(0x1b66b7651dbb92721c035c140d313b05a617c9df9c97b0ed4cc27226d9107118), MerkleHashOrchard(0x3b4564b91762fb4b354bab9090e3fa6611bec6af2c04c20c8b144f36bead983f), MerkleHashOrchard(0x0fec4763bc96f603590823c9660544edf425bdb3e0734973f136f90dd1dbf863), MerkleHashOrchard(0x34dcf5b7ecb1dda089e3cb6d0678e464e5fa8d146835315a886140ac3e168221), MerkleHashOrchard(0x31d3a638278b57a2923bc1ac63da2789d61aaa069e1fcdf9f3a3181968c09dbd), MerkleHashOrchard(0x2e8d63c774216c4b093197923c2255d39ce6a93d3386a93b5eb97f3b95ed2cca), MerkleHashOrchard(0x1a4e1a33a59cc1c3bd78771168f6ab8d24ee714d09e0e1aa459e6fb5964b3555), MerkleHashOrchard(0x05f71033d378bb729e90f578654694e692acc541cacaffdea045a02a4cb09770), MerkleHashOrchard(0x012e36772839eb54c3f50a619a59c57acbe5e8223f7a8610d43b81ff21681de8), MerkleHashOrchard(0x24d86d9aaaad5838a6d179cb5c2a3b8c80fd3849c9fdc4b896497c7f56e87d15), MerkleHashOrchard(0x0b5d7773fe73ed739820ebe6eafc1859278bf9c49546122cc12061cd51ce1ffe), MerkleHashOrchard(0x2d0a3ab6ae0a5a33b346835b4e3252b137ff3010fa0c4df7692601122998911f), MerkleHashOrchard(0x22559754c745c606ec0a54140795eda7bebfbb3c18961393a37df12af515ec5d), MerkleHashOrchard(0x258a081b5900f6074c3a94da3cc613b61758cc331d94ee75ab3b461dd92aaee8), MerkleHashOrchard(0x0f06d046da76daf00097e8af438215b183a518a5f423687696f5ce71e3de3fd5), MerkleHashOrchard(0x2ed66b6b6f8f29b6b3f625e8fe886221ebec30c729e8619a4c91e7ef4c44d215), MerkleHashOrchard(0x3f25121b0218dc6cf514fdb8e5d9a3b685d60e6b6baa837aea10aaa017a6574c), MerkleHashOrchard(0x27ba14a06cf07323de77da59259e3523acb269d955be20791a83bd195c91d43f), MerkleHashOrchard(0x2a4c109fe28f5c71f7bda83f74ec8b684cb90e8462772b224449ee07cd63d087)], position: Position(13) })
 right: None
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------

**Comment by fluidvanadium** [comment]
https://github.com/zingolabs/zingolib/pull/1482/files#diff-a43d5bf15e2e184dceaa23ce891791d4b96af3a60a0ad3b4d873600f114f1ac7
