### ISSUE TITLE
Error sending transaction: `send EmptyList`

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#1556]
We got this error randomly a few times. Trying again a little bit after works perfectly. 

![signal-2024-11-28-153153](https://github.com/user-attachments/assets/ca6e989b-8a12-4519-bce5-ebd0d0bb2923)

**Comment by juanky201271** [comment]
Well, We received a few emails with this problem, I can see in some screenshots that happen when the spendable amount is `red` -> this means the wallet is still confirming the last transaction. Also I can see in the screenshots that the wallet is fully synced.
@zancas @Edicksonjga

**Comment by dismad** [comment]
This bug is in zingo-cli as well. Please watch this video from around the 12 minute mark to see the bug in action. It seems when a tx isn't formatted correctly, it results in the "EmptyList" error. Like above, simply resubmitting the tx in the correct format clears the error.

https://www.youtube.com/watch?v=b5dIuGstMvI

**Comment by juanky201271** [comment]
@dismad thanks for reporting, and thanks for the tutorial, it is really useful. Can you share the info from the command `version` in zingo-cli when you hit this bug? thanks in advance.

**Comment by dismad** [comment]
`1.10.0-0-g7191addc` , and this is running on a raspi5

**Comment by juanky201271** [comment]
Thanks, we are trying to reproduce this error with the last dev `tag` in zingolib `1.10.3`, but no luck for now.

**Comment by dismad** [comment]
Ill update and try as well, thank you

**Comment by dismad** [comment]
As of version: `1.10.3-90-gc0de3b8c`

The issue that was noted in the video has been fixed! TY :)

**Comment by juanky201271** [comment]
Thanks @dismad, since we cannot reproduce this error in the latest version of zingolib... closing...
