### ISSUE TITLE
I cannot yet see line by line coverage in firefox here:

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#16]
https://app.codecov.io/gh/zingolabs/zecwallet-light-cli/blob/90b4c42b57476f7f32572e08dd9a33c8ce7cafac/lib/src/lightclient.rs

**Comment by zancas** [comment]
I just refreshed the page...   and it appears to work...  so there's some issue with the server.

**Comment by AloeareV** [comment]
Odd. At some point it started working on our firefoxes. Don't know why it was failing. Will leave this open for a while, as this was some spooky action at a distance going on.

**Comment by dannasessha** [comment]
Over a month since last post, haven't heard of this particular issue though codecov is still causing us some troubles IIUC.

Closing for the moment to tidy up.
