### ISSUE TITLE
Make arguments for launching `lightwalletd` and `zcashd` with configuration files using `cli` flags

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#17]
Requesting further comments, or details to follow.

Posting here a message I've received:  "Why not pass the zcashd and lightwalletd binaries to --regtest as arguments? Force a user to figure out where to get those binaries from..."

Sounds fairly reasonable to me. I could probably easily also include default values that fail if they don't find something.

**Comment by zancas** [comment]
Adding defaults is not something to take lightly.  I know experienced programmers who vehemently opine that there should be no such thing as defaults.

In any event, let's _NOT_ add defaults to any initial implementation.

**Comment by dannasessha** [comment]
10-4.

**Comment by dannasessha** [comment]
From another conversation:  "enabling `zingo-cli` to launch `zcashd` and `lightwalletd` (properly confiured) in regtest mode would help."

**Comment by zancas** [comment]
I think the right pattern might be:

The User has to move the `zcashd` and `lightwalletd` binaries into `regest` in standard locations.   Then when `zingo-cli --regtest` is invoked it simply looks in the standard spot.   No need for new arguments.

**Comment by dannasessha** [comment]
I think this done with #26 !
