### ISSUE TITLE
Using flags, allow use of various network types on invocation the `cli` client

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#19]
A user should be able to define which network to use (among testnet, regtest, main, and fakemainnet, which correspond to the Enums of the same names) using flags on the cli.

I would also like to include a message confirming this setting to the user during startup, and possible on the "command line" of the cli-interface after startup. Some of this is already in place, but it should be systematic coverage, and make sense to users and developers alike.

**Comment by AloeareV** [comment]
Added...some number of months ago.
