### ISSUE TITLE
Our `librustzcash` dep needs consideration

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#25]
I saw a commit message on `librustzcash` that said `Return the network type for encoding addresses as part of the network… …parameters.` and the [changed code in that commit](https://github.com/zcash/librustzcash/commit/94c8d8e7ef2a4a3492ad5d35daa1c548855f9277) looked like something I was working with very recently.

I then noticed our repo is pointing to a week-old commit on that same repo, hardcoded as a [patch in Cargo.toml](https://github.com/zingolabs/zingolib/blob/dev/Cargo.toml).

With work happening so close to a rapidly moving library, I thought I would point this out, and see if we should adjust this setting.

For example, I'm not sure if the code I wrote a couple days ago would still be working with this update.

Feel free to close this issue if there's no problem, and/or we could use this space to discuss.

**Comment by zancas** [comment]
Did you test it, to see if the update effected the behavior of your `regtest` `zingo-cli`?

**Comment by dannasessha** [comment]
> Did you test it, to see if the update effected the behavior of your `regtest` `zingo-cli`?

I did not.
