### ISSUE TITLE
Error sending in a call from zingo-pc

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#269]
When I try to send with `execute("send", JSON)` I got this error:

```
{
  "error": "The system cannot find the file specified. (os error 2)"
}
```

I guess the problem is when the command `send` try to access to some file...

**Comment by juanky201271** [comment]
I put this `default-features=true` in cargo.toml... and It seems like is sending... but I got the famous BOBA error...

![image](https://user-images.githubusercontent.com/43755989/222922343-cd51f320-2fed-4fc6-ad94-58eb5187f95d.png)

**Comment by juanky201271** [comment]
How to reproduce: Really easy.

OS: Windows 11

1. yarn install
2. yarn build
3. yarn start
4. try to send to an full UA.

That's it.

**Comment by juanky201271** [comment]
How to reproduce: Really easy.

OS: Windows 11 (64 bits) WSL

Rust: `nightly-x86_64-unknown-linux-gnu - rustc 1.70.0-nightly (f15f0ea73 2023-03-04)`

1. yarn install
2. yarn build
3. yarn start
4. try to send to an full UA.

That's it.

**Comment by juanky201271** [comment]
How to reproduce: Really easy.

MacOS: Ventura 13.1

Rust: `nightly-aarch64-apple-darwin- rustc 1.70.0-nightly (f15f0ea73 2023-03-04)

1. yarn install
2. yarn build
3. yarn start
4. try to send to an full UA.

That's it.

**Comment by nuttycom** [comment]
The cause of this is the use of rustc 1.70.0-nightly. This will be resolved by https://github.com/zcash/halo2/pull/739

**Comment by juanky201271** [comment]
@nuttycom Thanks for the info, what a relief, because I have no idea what's going on... :D

**Comment by zancas** [comment]
@juanky201271 @nuttycom what's the status of this issue?   Should it be closed?

**Comment by juanky201271** [comment]
> @juanky201271 @nuttycom what's the status of this issue? Should it be closed?

oh, yes, I think so...

**Comment by juanky201271** [comment]
this is fixed. closing...
