### ISSUE TITLE
Is there a use-case that would justify chain-specific clients?

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#278]
This match, for example is only necessary because we're accounting for different chains.   In practice most compiled clients will be used with a specific chain (e.g. `mainnet`, `regtest`).   Perhaps the chain-specific code should be selected at compile time.

**Comment by AloeareV** [comment]
I for one very much being able to point at a testnet instance without needing to pass compile-time arguments to zingo-cli

**Comment by zancas** [comment]
I think that an option to compile a binary without a `do_send` attack surface need not reduce flexibility.   I guess we should be mindful that we want to produce a new option that's a lower capability binary, rather than reduce the capabilities of more general binaries.

**Comment by pacu** [comment]
I'd advice against this. We've worked with network-dependent builds on the early days of the mobile SDKs and it's really chaotic.
