### ISSUE TITLE
zcash doesn't send "from" addresses, and doesn't have UTXOs

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#32]
The readme has confusing terminology here:

https://github.com/zingolabs/zingolib#note-management

We could call the analog of a Bitcoin UTXO a ZUTXO.

There's no notion of a "sender's address" in a zcash transaction.

**Comment by AloeareV** [comment]
> There's no notion of a "sender's address" in a zcash transaction.
 There is if you're sending from a t-address.
