### ISSUE TITLE
There are (at least) two available forks of lightwalletd

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#37]
https://github.com/adityapk00/lightwalletd

AND

https://github.com/zcash/lightwalletd

We need to choose one, clearly indicate the choice, and target it exclusively.

**Comment by zancas** [comment]
This bug report might provide a criteria for choosing between the alternatives:
https://github.com/adityapk00/zecwallet-lite/issues/156#issue-1245759918

**Comment by AloeareV** [comment]
My instinct is to target upstream, without _very_ convincing benefits to using aditya's. It's yet another large codebase to keep up with maintenance of in a language I don't believe any of us are particularly experienced with, which is in my opinion a very large downside, especially given the scale of what we're already trying to get up to speed with.

**Comment by zancas** [comment]
I tentatively agree...  but mostly think we need more evidence/data.

**Comment by zancas** [comment]
This bugfix seems to argue in favor of the `zcash` variant:

https://github.com/zcash/lightwalletd/releases/tag/v0.4.11

**Comment by dannasessha** [comment]
We've moved to `zcash`'s version, though we are still fiddling with which branch should use which dependency branch or commit.

Closing.
