### ISSUE TITLE
There should be a port of, or a paper trail to, older issues.

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#4]
Recently this repo "moved" from another location, which had [several dozen open issues](https://github.com/zingolabs/zingolib_original/issues). We should either port those issues over here (time consuming, maybe not needed) or at least leave a paper trail to them.

The link above points to the issue, so this issue issue itself could serve as a makeshift paper trail.

**Comment by dannasessha** [comment]
Bumping.

**Comment by dannasessha** [comment]
I think it would be cool if we wanted to try to port that stuff, when there's time: revisit them and decide what's still relevant and priority.

**Comment by zancas** [comment]
You could check for a github button that lets you fork/clone issues..  but that seems improbably.   We can just keep that repo as is...
