### ISSUE TITLE
Detach `--regtest` from local zcashd environment setup

### ISSUE THREAD

**Issue by pacu** [zingolabs/zingolib#451]
Since `RegtestManager` was introduced, Zingolib attempts to start up the cache <> zcashd <> lightwalletd  setup. 

This breaks the darksidewalletd tests on regtest since `RegtestManager` kicks in when the `--regtest` flag is specified.

In order to be able to point to a `lightwalletd` server in `--darkside-very-insecure` mode this has to be modified so callers 
can tell Zingolib that they won't be needing the `RegtestManager` at all.

**Comment by zancas** [comment]
I believe that @AloeareV proposed that we close this?
