### ISSUE TITLE
Error Shielding Transaction

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#455]
Shielding: `all` and `sapling`:
failed to compute sapling witness: Unable to compute root; missing values for nodes [Address { level: Level(10), index: 70560 }]

![image](https://github.com/zingolabs/zingolib/assets/43755989/6e1635b7-5a61-4837-b50f-8e4d6323aa30)

**Comment by juanky201271** [comment]
Shielding: `transparent`
Error: SendResponse { error_code: -26, error_message: "16: bad-txns-orchard-unknown-anchor" }

![image](https://github.com/zingolabs/zingolib/assets/43755989/f876bf3d-1384-4974-bbe6-d4cd23b81db2)

**Comment by juanky201271** [comment]
related with: https://github.com/zingolabs/zingo-pc/issues/98
same wallet.

**Comment by james-katz** [comment]
I'm getting the same error `{ error_code: -26, error_message: "16: bad-txns-orchard-unknown-anchor" }` with my [zingolib-wrapper](https://github.com/james-katz/zingolib-wrapper) when trying to send a transaction.
The weird part is my wrapper works ok on my machine, I only get this error when using it on cloud lightsail instance, maybe a memory issua? My instace has only 2 gb of ram.

uname -a
Linux cloud-amd64 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

**Comment by zancas** [comment]
What's the status of this issue?   Should it still be open?

**Comment by juanky201271** [comment]
> I'm getting the same error `{ error_code: -26, error_message: "16: bad-txns-orchard-unknown-anchor" }` with my [zingolib-wrapper](https://github.com/james-katz/zingolib-wrapper) when trying to send a transaction. The weird part is my wrapper works ok on my machine, I only get this error when using it on cloud lightsail instance, maybe a memory issua? My instace has only 2 gb of ram.
> 
> uname -a Linux cloud-amd64 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

@james-katz Can you confirm this bug is already fixed? Thanks in advance. (I mean, using the last commit of zingolib/dev)

**Comment by juanky201271** [comment]
Well, I can confirm this issue is fixed, I can shield & send with the last zingolib/dev commit... closing, and thanks @james-katz for reporting.

**Comment by james-katz** [comment]
Sorry for the late reply, yes apparently it's fixed.
```
2023-10-05T21:17:47.209440Z  INFO zingolib::wallet: 0: Creating transaction sending 50000 zatoshis to 1 addresses    
2023-10-05T21:17:49.465436Z  INFO zingolib::wallet: 2: Adding outputs    
2023-10-05T21:17:49.466817Z  INFO zingolib::wallet: Selected notes worth 69293503    
2023-10-05T21:17:49.466843Z  INFO zingolib::wallet: 2: Adding 0 sapling notes, 1 orchard notes, and 0 utxos    
2023-10-05T21:17:49.467599Z  INFO zingolib::wallet: 2: selecting notes    
2023-10-05T21:17:49.467645Z  INFO zingolib::wallet: Adding orchard spend    
2023-10-05T21:17:52.029169Z  INFO zingolib::wallet: 5: Building transaction    
2023-10-05T21:18:03.842069Z  INFO zingolib::wallet: 16: Transaction created    
2023-10-05T21:18:03.842095Z  INFO zingolib::wallet: Transaction ID: a4af7cdd7f47ec74dd9f72e58bc3b4e797b8f020168c3e05a32dc3d9f1e25f70
```
No errors after Transaction ID.

**Comment by juanky201271** [comment]
> Sorry for the late reply, yes apparently it's fixed.
> 
> ```
> 2023-10-05T21:17:47.209440Z  INFO zingolib::wallet: 0: Creating transaction sending 50000 zatoshis to 1 addresses    
> 2023-10-05T21:17:49.465436Z  INFO zingolib::wallet: 2: Adding outputs    
> 2023-10-05T21:17:49.466817Z  INFO zingolib::wallet: Selected notes worth 69293503    
> 2023-10-05T21:17:49.466843Z  INFO zingolib::wallet: 2: Adding 0 sapling notes, 1 orchard notes, and 0 utxos    
> 2023-10-05T21:17:49.467599Z  INFO zingolib::wallet: 2: selecting notes    
> 2023-10-05T21:17:49.467645Z  INFO zingolib::wallet: Adding orchard spend    
> 2023-10-05T21:17:52.029169Z  INFO zingolib::wallet: 5: Building transaction    
> 2023-10-05T21:18:03.842069Z  INFO zingolib::wallet: 16: Transaction created    
> 2023-10-05T21:18:03.842095Z  INFO zingolib::wallet: Transaction ID: a4af7cdd7f47ec74dd9f72e58bc3b4e797b8f020168c3e05a32dc3d9f1e25f70
> ```
> 
> No errors after Transaction ID.

Thanks...
