### ISSUE TITLE
New field for fee in the JSON object when using `send` command

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#466]
I think the possibility of `send` from `zingolib` with a specific `fee`, besides the ZIP317... it's a good feature.

Ref PR: https://github.com/zingolabs/zingo-mobile/pull/499
Ref Issue: https://github.com/zingolabs/zingo-mobile/issues/488

**Comment by zancas** [comment]
We're not going to support non-317 fees, for now.

**Comment by juanky201271** [comment]
Let's go close the others related issue & PR... just for coherence...
