### ISSUE TITLE
Is recover implemented?  If not, we should implement and test

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#47]
Step (0) try to run it in regtest mode in various ways.

For example, with a wallet that contains a seed!

Step (1) run all the tests under `tarpaulin` to see if any test hits it.

Step (d) Consider what we've learned from previous steps and write it down here!

**Comment by dannasessha** [comment]
I'd love to see this actually work! That would be huge for users who want to migrate to Zingo.

**Comment by zancas** [comment]
Don't let me stop you.
