### ISSUE TITLE
We need to fix some names/comments

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingolib#54]
Incomplete list: https://github.com/zingolabs/zingolib/blob/ddf8261a2a6aabb5a1fb8b46d450d7ed5aee339c/lib/src/blaze/block_witness_data.rs#L37
This should be named something more like wallet_local_blocks
https://github.com/zingolabs/zingolib/blob/ddf8261a2a6aabb5a1fb8b46d450d7ed5aee339c/lib/src/blaze/block_witness_data.rs#L39-L41
"The function"?

**Comment by zancas** [comment]
This fn:
https://github.com/zingolabs/zingolib/pull/43/files#diff-5db81553e9ad3ef3f61c863862a9faa9ed3a65df4d7698dcd65c3eb4d0a66b28R222

requires the note description to `have_spending_key`...

Perhaps the fn should be named:   `get_spendable_notes`

Notes that are `spent.is_none` and `.have_spending_key` and `!wtx.unconfirmed` and `witnesses.len() > 0` should be spendable.

**Comment by zancas** [comment]
This comment and this fn could be improved.

https://github.com/zingolabs/zingolib/pull/43/files#diff-5db81553e9ad3ef3f61c863862a9faa9ed3a65df4d7698dcd65c3eb4d0a66b28R394

**Comment by zancas** [comment]
This line of code:

https://github.com/zingolabs/zingolib/pull/43/files#diff-5db81553e9ad3ef3f61c863862a9faa9ed3a65df4d7698dcd65c3eb4d0a66b28R453

convinces me that `WalletTx` should be `TransactionMetaData`

**Comment by zancas** [comment]
https://github.com/zingolabs/zingolib/pull/43/files#r928021810

**Comment by zancas** [comment]
In future this level of refactor will be handled in the course of other development.  We won't open issues for this kind of change.
