### ISSUE TITLE
Error with Sapling Balance

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#560]
In some cases zingo-mobile is misreporting the sapling balance:

https://github.com/zingolabs/zingo-mobile/issues/533

@juanky201271 can you test this via @Oscar-Pepper 's "regchest":  https://github.com/zingolabs/zingo-regchest ?

**Comment by juanky201271** [comment]
for the test I need to have funds in the three pools, and then I need to shield the transparent pool & to upgrade the sapling pool or send to self from sapling to orchard in different transactions, @Oscar-Pepper maybe you an idea of how to build that new scenario in zingo-testutils...

**Comment by juanky201271** [comment]
The test is done: https://github.com/zingolabs/zingo-mobile/pull/536

**Comment by juanky201271** [comment]
@zancas I asked to @edicksonjga about this issue...

**Comment by fluidvanadium** [comment]
im curious about this issue

**Comment by zancas** [comment]
@juanky201271 are we awaiting @Edicksonjga for some tests of this?

**Comment by Edicksonjga** [comment]
> @juanky201271 are we awaiting @Edicksonjga for some tests of this?

It keeps crashing, more than 80 thousand blocks synchronized and the balance in sapling is wrong after a synchronization in the background and opening the app several times.

![Screenshot_20231101-142440.jpg](https://github.com/zingolabs/zingolib/assets/37910384/9a426e67-1ac8-4741-898d-476f45b3fd26)

![Screenshot_20231101-142444.jpg](https://github.com/zingolabs/zingolib/assets/37910384/410fdb9a-2f82-4d2a-9891-b66006879adf)

The actual balance in that wallet is 0.01135001 ZEC in Sapling.

@zancas @juanky201271

**Comment by zancas** [comment]
Hi @Edicksonjga can you please post the version information field, that has the build commit hash?

**Comment by Edicksonjga** [comment]
> Hi @Edicksonjga can you please post the version information field, that has the build commit hash?

![Screenshot_20231101-145211.jpg](https://github.com/zingolabs/zingolib/assets/37910384/09b8d9ee-caa0-48e8-a757-b43ffa27926e)

Last beta version that @juanky201271 has shared with me today. @zancas

**Comment by Edicksonjga** [comment]
> @juanky201271 are we awaiting @Edicksonjga for some tests of this?

The same problem is also still present in Zingo PC, balance error in Sapling. @zancas @juanky201271 
![Captura de pantalla de 2023-11-01 17-06-54](https://github.com/zingolabs/zingolib/assets/37910384/d1730cc2-f3c8-4145-b130-7d842d6ea926)
![Captura de pantalla de 2023-11-01 17-07-00](https://github.com/zingolabs/zingolib/assets/37910384/882ee173-837e-4386-a7ca-06a9a0f4a43b)

**Comment by Oscar-Pepper** [comment]
we can use regchest to load the wallet from a saved file but i imagine when the app goes into the background this is not the case. i think end-to-end tests might be our best shot at catching this one. @juanky201271 what do you think? you know more about the the react-native layer and background tasking

**Comment by juanky201271** [comment]
> we can use regchest to load the wallet from a saved file but i imagine when the app goes into the background this is not the case. i think end-to-end tests might be our best shot at catching this one. @juanky201271 what do you think? you know more about the the react-native layer and background tasking

IMO we have two issues now (balance is wrong when syncing & the new tx disappears when you stop-start the Apps, both) and I bet you those are related with the same event: close/open a RCP session. It is simple. But the important thing is: What happen in the three pieces when you kill/create a new session with the server? We need to study all of there steps carefully IMO. You are right e2e test can be the best tool for this research...

**Comment by zancas** [comment]
@Edicksonjga is this issue still active?   How can we tell?   Did someone write code to fix it?  @fluidvanadium @AloeareV @Oscar-Pepper ?

Is there a merged PR somewhere that *SHOULD* say `Fixes: #560` ?

**Comment by Edicksonjga** [comment]
> @Edicksonjga is this issue still active?   How can we tell?   Did someone write code to fix it?  @fluidvanadium @AloeareV @Oscar-Pepper ?
> 
> Is there a merged PR *WITH A TEST* somewhere that *SHOULD* say `Fixes: #560` ?

The error was corrected in the last release! 🥳🥳 @zancas
