### ISSUE TITLE
Wrong balance on sapling - unstable connection

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingolib#572]
### Bug in the balance after synchronisation #560

I have been running several tests on ZingoPC and Zingo Mobile, one of the main bugs is the wrong balance in Sapling when the internet connection is unstable.

The bug is still present in ZingoPC and Zingo Mobile running on the latest version of zingolib. 

#### Some images:
![Captura de pantalla de 2023-10-05 09-22-55](https://github.com/zingolabs/zingolib/assets/37910384/46ae5f46-7ab8-4297-bfdd-8b8534666f0f)
![Screenshot_20231005-002949](https://github.com/zingolabs/zingolib/assets/37910384/6708a08e-0b13-42ef-bbed-56dd91ec5853)
_**The correct balance in the wallet is 0.0003 ZEC in Orchard.**_

Previously, when the internet connection was lost and came back, the synchronisation would not start, and you had to close and open zingopc again. Now when the internet comes back, the synchronisation starts again and the progress is shown by the percentage, **but there is still an bug in the balance when the synchronisation is finished.**

Linux Mint 21.2
Zingo PC 1.0.3 / Zingo Mobile 1.2.5 (126)
zingolib mob-prerelease-1.3.0-63-gd3233715

**Comment by AloeareV** [comment]
@Edicksonjga Is this still active? This is a regression from release?

**Comment by Edicksonjga** [comment]
> @Edicksonjga Is this still active? This is a regression from release? 

Yes, the error is still there and no matter how many times I try it in Production, it doesn't happen. @AloeareV

**Comment by juanky201271** [comment]
this is related with: https://github.com/zingolabs/zingo-mobile/issues/533

**Comment by Edicksonjga** [comment]
> this is related with: https://github.com/zingolabs/zingo-mobile/issues/533

Yes, and is being followed up on:


https://github.com/zingolabs/zingolib/issues/560

**Comment by Oscar-Pepper** [comment]
ok overview/update:
as a result of further testing by @Edicksonjga, this bug has seemingly been narrowed down to a single transaction in a much smaller test wallet. the bug appears due to regular network interruptions while syncing and causes a 0.0001 fee from a send-to-self transaction to change to a receive of 0.0001 zec, therefore resulting in a 0.0002 zec excess in the final balance.

test wallet seed: drive celery ...
max known birthday to reproduce bug: 2295000
expected final balance: 0.000 zec
balance when bug is hit: 0.0002 zec
bugged transaction: d8ca1781adda081cd8a095cb3c24a29efc2542aa751ec5812f6ddaf50af7afd1

**Comment by Oscar-Pepper** [comment]
![image](https://github.com/zingolabs/zingolib/assets/109323234/114168df-d6f9-4b78-99f9-2824be3d24d8)

**Comment by Oscar-Pepper** [comment]
@Edicksonjga could you verify this is correct and maybe add you own report of your findings with as much detail as possible?

**Comment by Edicksonjga** [comment]
> @Edicksonjga could you verify this is correct and maybe add you own report of your findings with as much detail as possible?

Thank you very much @Oscar-Pepper, yes, the summary you provide is correct.

I have been testing with the version that @fluidvanadium passed me and with the wallet you mention, synchronizing from a recent block height (November 2023) and obtaining in the synchronization the last 22 transactions.

At the end of synchronization the balance should be zero, but due to the error caused by interrupting the synchronization, the balance is 0.0002 ZEC in Sapling and the only transaction that changes is the one you mention that instead of being an Send-to-Self is reflected as a Received transaction.

**Comment by Oscar-Pepper** [comment]
i also discovered a possible bug that may be related while comparing zingo-cli `summaries` command with a emulated mobile app:

the second transcation after the bugged tx (d8ca178) is the first tx in the wallet to show the `send-to-self` value transfer in zingo-cli. all previous send-to-selfs (at least as shown as send-to-self in the mobile app) only show the `fee` value transfer, including the tx displaying the balance bug. after this first send-to-self value transfer, it seems like some send-to-selfs are missing the send-to-self value transfer (only showing the fee) and some send-to-selfs show both a send-to-self and fee value transfer.

wallet: drive celery
bday: 2295000
first transaction with send-to-self value transfer: a1ed0c0e0742613732d761c91cf6492362f132b0884a06b53af56be1176dbecf

**Comment by juanky201271** [comment]
Since my first time using `summaries` I noticed that, sometimes I got only 1 tx with the same txid with `fee`, missing the other tx with `sendtoself`... In fact in the zingo-mobile code when happend that the App consider this tx as `sendtoself` directly.

**Comment by Oscar-Pepper** [comment]
oh ok good to know you were aware

**Comment by Oscar-Pepper** [comment]
> i also discovered a possible bug that may be related while comparing zingo-cli `summaries` command with a emulated mobile app:
> 
> the second transcation after the bugged tx (d8ca178) is the first tx in the wallet to show the `send-to-self` value transfer in zingo-cli. all previous send-to-selfs (at least as shown as send-to-self in the mobile app) only show the `fee` value transfer, including the tx displaying the balance bug. after this first send-to-self value transfer, it seems like some send-to-selfs are missing the send-to-self value transfer (only showing the fee) and some send-to-selfs show both a send-to-self and fee value transfer.
> 
> wallet: drive celery bday: 2295000 first transaction with send-to-self value transfer: a1ed0c0e0742613732d761c91cf6492362f132b0884a06b53af56be1176dbecf

on further investigation, the send-to-self value transfer only are created when there is outgoing metadata. sorry for the noise but this is unlikely to help this bug hunt

**Comment by Edicksonjga** [comment]
I'll close that report, I hope I never open it again 😁😁. @juanky201271 @zancas @fluidvanadium @Oscar-Pepper @AloeareV ...
