### ISSUE TITLE
Restarting the connection with the server, change some transactions with amount errors.

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#665]
How to reproduce:
- rescan a wallet
- finish/close the App
- re-start the App
- wait to connect with the server
- some send-to self txs have incorrect amount. In this case the first tx changed from 0.0001 (correct value) to 0.00032 (incorrect value).

PS: I'm sure I can reproduce the same issue with `zingo-pc` & `zingocli`

https://github.com/zingolabs/zingolib/assets/43755989/53439692-9ba9-433b-aff3-65f3828791fb

**Comment by juanky201271** [comment]
Another test:
- I had 0.00044 in the transparent pool.
- I shielded the transparent pool.
- I got a tx `sendtoself` with amount 0 & fee 0.0001 -> correct.
- I restarted the App.
- The same `sendtoself` tx now with amount 0 & fee 0.00054 (0.00044 + 0.0001) -> incorrect.

![image](https://github.com/zingolabs/zingolib/assets/43755989/1ba17941-69d5-4594-b7c4-6b1a24218839)

**Comment by fluidvanadium** [comment]
@juanky201271 @Edicksonjga is this a regression or present on release?

**Comment by juanky201271** [comment]
IMO I see this sudden change of the fee all the time since `shartree` but in two different ways:
- at the beginning the change was from 0.0001 to an astronomic amount. (this was fixed).
- now the change is from 0.0001 to the shielded amount + the fee.

Even if those seem different, my feeling is they are related. I don't know if I asked your question. @fluidvanadium

**Comment by fluidvanadium** [comment]
i think the astronomic amount was fixed by #623
the next one, maybe it is small. we need to rethink our metadata storage.

**Comment by juanky201271** [comment]
> i think the astronomic amount was fixed by #623 the next one, maybe it is small. we need to rethink our metadata storage.

Oh, of course.. that was fixed & the duplicates were fixed as well...

**Comment by juanky201271** [comment]
Another thing I observed, maybe it's not that useful was: The first time I read a tx is correct... but if I kill the session with the server and I read the same tx now, is incorrect. This is like quantum physics...

**Comment by juanky201271** [comment]
Another piece of info:
- rescan put the correct data.
- restart the App.
- No syncing, I stooped the sync in debug to see when the tx changed.
- the tx becomes incorrect when the tx have one more confirmation (1 more block).
```
2023-11-11 09:20:52.827 12929-13021 ReactNativeJS           org.ZingoLabs.Zingo                  I  { txDetails: [ { address: '', amount: 0, memos: undefined } ],
                                                                                                      type: 'SendToSelf',
                                                                                                      confirmations: 2337,
                                                                                                      txid: 'ac602832c603105d10690f2cbd83bd822a8765749d348ad93c63f7656311e5c3',
                                                                                                      time: 1699543312,
                                                                                                      fee: 0.0001 }
2023-11-11 09:20:58.352 12929-13021 ReactNativeJS           org.ZingoLabs.Zingo                  I  { txDetails: [ { address: '', amount: 0, memos: undefined } ],
                                                                                                      type: 'SendToSelf',
                                                                                                      confirmations: 2338,
                                                                                                      txid: 'ac602832c603105d10690f2cbd83bd822a8765749d348ad93c63f7656311e5c3',
                                                                                                      time: 1699543312,
                                                                                                      fee: 0.00054 }

**Comment by juanky201271** [comment]
This is fixed with: https://github.com/zingolabs/zingolib/commit/44a371caa3cf9f0c076e927cf35a103fb96666fb.

Closing...
