### ISSUE TITLE
Fix Test `mempool_spends_correctly_marked_unconfirmed_spent` 

### ISSUE THREAD

**Issue by pacu** [zingolabs/zingolib#673]
Removal of function `do_save_to_buffer` broke `mempool_spends_correctly_marked_unconfirmed_spent`

`export_save_buffer_runtime` seems to be its replacement but it's not being use elsewhere and I can't figure how to fix this.

**Comment by juanky201271** [comment]
maybe this is helpful: https://github.com/zingolabs/zingo-mobile/pull/561/files#diff-4fe8b5135dd27e9e8239c61835dafa0713eea327d1f02b33f36d1ed9b17bb129R178

**Comment by fluidvanadium** [comment]
passes on dev today
