### ISSUE TITLE
README needs to be cleaned up

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingolib#7]
See #3 and its PR #5: Recently I've made some changes to the README, and I tried to improve and expand it where needed for accuracy or clarity.

However, in so doing, I have noticed that there should be a focused effort to make the README better, maybe only after some of the dust of changing so many things at once has settled.

For example, the first line of the README says
```
This repo provides both a library for zingoproxyclient and zingo-mobile, as well as an included cli application to interact with zcashd via lightwalletd.
```
"zingoproxyclient" isn't a repo we currently have, so we need to evaluate the language here.

Some warnings are redundant, or maybe in the wrong place...

The two functions of the repo may not be clear...

@zancas has left some additional comments on #5 about terminology...

**Comment by dannasessha** [comment]
Tracking possible issues:
[Protobuf Compiler](https://github.com/zingolabs/zingolib#compiling-from-source) from https://github.com/zingolabs/zingolib#compiling-from-source
[suggesting zingo's lightwalletd](https://github.com/zingolabs/zingolib#notes) from https://github.com/zingolabs/zingolib#notes

**Comment by zancas** [comment]
I don't think those hyperlinks are pointing to their intended targets.
