### ISSUE TITLE
Observed crash in IOS Xcode

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#826]
![google_play_panic](https://github.com/zingolabs/zingolib/assets/640955/526cc57b-227c-427e-b96f-6e2c37a24cdb)

I hypothesize that this panic is caused by a panic in start_sync

https://github.com/zingolabs/zingolib/blob/f8c914a5894fd448d1b77556ad239c1f4f0ddad2/zingolib/src/lightclient.rs#L1388

**Comment by juanky201271** [comment]
solved.
